name: continuous integration & continuous delivery

# https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
on:
  workflow_call:
    inputs:
      WORKFLOW_ENV:
        required: true
        type: string
        description: "can be production/offline/development"
      PROJECT:
        required: true
        type: string
        description: "name of the project"
      CI_SERVER:
        required: true
        type: string
        description: "name of the runner which runs CI processes"
      CD_SERVER:
        required: true
        type: string
        description: "name of the runner - which hosts your app"
      SKIP_CD:
        required: true
        type: boolean
        description: "whether to skip CD (optional)"
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      DOCKERHUB_REPO:
        required: true
      USER:
        required: true
      USER_TOKEN:
        required: true
      MARIADB_PASS:
      SITE_DEFAULT_PASS:

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    with:
      WORKFLOW_ENV: ${{ inputs.WORKFLOW_ENV }}
      CI_SERVER: ${{ inputs.CI_SERVER }}
      PROJECT: ${{ inputs.PROJECT }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
      USER: ${{ secrets.USER }}
      USER_TOKEN: ${{ secrets.USER_TOKEN }}

  cd:
    if: ${{ inputs.SKIP_CD == false }}
    needs: ci
    uses: ./.github/workflows/cd.yaml
    with:
      WORKFLOW_ENV: ${{ inputs.WORKFLOW_ENV }}
      PROJECT: ${{ inputs.PROJECT }}
      CD_SERVER: ${{ inputs.CD_SERVER }} # can be changed
    secrets:
      MARIADB_PASS: ${{ secrets.MARIADB_PASS }}
      SITE_DEFAULT_PASS: ${{ secrets.SITE_DEFAULT_PASS }}
